export const FETCHING_LIST = 'FETCHING_LIST'
export const FETCHING_LIST_SUCCESS = 'FETCHING_LIST_SUCCESS'
export const FETCHING_LIST_FAILURE = 'FETCHING_LIST_FAILURE'

export const FETCHING_MOVIE_DETAILS = 'FETCHING_MOVIE_DETAILS'
export const FETCHING_MOVIE_DETAILS_SUCCESS = 'FETCHING_MOVIE_DETAILS_SUCCESS'
export const FETCHING_MOVIE_DETAILS_FAILURE = 'FETCHING_MOVIE_DETAILS_FAILURE'


export const FETCHING_CAST_PICS = "FETCHING_CAST_PICS";
export const FETCHING_CAST_PICS_SUCCESS = "FETCHING_CAST_PICS_SUCCESS";
export const FETCHING_CAST_PICS_FAILURE = "FETCHING_CAST_PICS_FAILURE";

export const IMAGE_BASE_URL = 'http://image.tmdb.org/t/p/w185'
export const IMAGE_BASE_URL_500 = 'http://image.tmdb.org/t/p/w500'

export const FETCHING_CAST_LIST = 'FETCHING_CAST_LIST'
export const FETCHING_CAST_LIST_SUCCESS = 'FETCHING_CAST_LIST_SUCCESS'
export const FETCHING_CAST_LIST_FAILURE = 'FETCHING_CAST_LIST_FAILURE'
export const API = 'FETCHING_CAST_LIST_FAILURE'


export const FETCHING_PEOPLE_IMAGE_LIST = 'FETCHING_PEOPLE_IMAGE_LIST'
export const FETCHING_PEOPLE_IMAGE_SUCCESS = 'FETCHING_PEOPLE_IMAGE_SUCCESS'
export const FETCHING_PEOPLE_IMAGE_FAILURE = 'FETCHING_PEOPLE_IMAGE_FAILURE'

export const FETCHING_VIDEO_LIST = 'FETCHING_VIDEO_LIST'
export const FETCHING_VIDEO_SUCCESS = 'FETCHING_VIDEO_SUCCESS'
export const FETCHING_VIDEO_FAILURE = 'FETCHING_VIDEO_FAILURE'

export const FETCHING_MOVIE_DATA = 'FETCHING_MOVIE_DATA'
export const FETCHING_MOVIE_DATA_SUCCESS = 'FETCHING_MOVIE_DATA_SUCCESS'
export const FETCHING_MOVIE_DATA_FAILURE = 'FETCHING_MOVIE_DATA_FAILURE'

export const FETCHING_PEOPLE_DETAILS_LIST = 'FETCHING_PEOPLE_DETAILS_LIST'
export const FETCHING_PEOPLE_DETAILS_SUCCESS = 'FETCHING_PEOPLE_DETAILS_SUCCESS'
export const FETCHING_PEOPLE_DETAILS_FAILURE = 'FETCHING_PEOPLE_DETAILS_FAILURE'

export const FETCHING_PEOPLE_TVSHOW_LIST = 'FETCHING_PEOPLE_TVSHOW_LIST'
export const FETCHING_PEOPLE_TVSHOW_SUCCESS = 'FETCHING_PEOPLE_TVSHOW_SUCCESS'
export const FETCHING_PEOPLE_TVSHOW_FAILURE = 'FETCHING_PEOPLE_TVSHOW_FAILURE'

export const FETCHING_PEOPLE_MOVIES_LIST = 'FETCHING_PEOPLE_MOVIES_LIST'
export const FETCHING_PEOPLE_MOVIES_SUCCESS = 'FETCHING_PEOPLE_MOVIES_SUCCESS'
export const FETCHING_PEOPLE_MOVIES_FAILURE = 'FETCHING_PEOPLE_MOVIES_FAILURE'
export const GRID_DATA = 'GRID_DATA'
export const LIST_DATA = 'LIST_DATA'

export const FETCHING_SIMILAR_MOVIE_LIST = 'FETCHING_SIMILAR_MOVIE_LIST'
export const FETCHING_SIMILAR_MOVIE_LIST_SUCCESS = 'FETCHING_SIMILAR_MOVIE_LIST_SUCCESS'
export const FETCHING_SIMILAR_MOVIE_LIST_FAILURE = 'FETCHING_SIMILAR_MOVIE_LIST_FAILURE'